[package]
name = "bop-executor-macro"
version = "0.1.0" # Should be kept in sync with `pollster`
description = "Proc-macro crate for bop-executor"
categories = ["asynchronous", "concurrency"]
keywords = ["async", "minimal", "executor", "runtime", "block_on"]
repository = "https://github.com/zesterer/pollster"
authors = []
edition = "2024"
license = "Apache-2.0/MIT"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = { version = "1", default-features = false }
syn = { version = "2", default-features = false, features = [
    "full",
    "parsing",
    "printing",
] }

[dev-dependencies]
bop-executor = { path = "..", features = ["macro"] }

[package.metadata.docs.rs]
targets = []
