name: Docs Markdown Lint

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'scripts/docs_markdownlint.sh'
      - '.github/workflows/docs-lint.yml'
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'scripts/docs_markdownlint.sh'
      - '.github/workflows/docs-lint.yml'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install markdownlint
        run: npm install --global markdownlint-cli@0.39.0
      - name: Run markdownlint
        run: scripts/docs_markdownlint.sh
